SEED: 42
CHECKPOINT_PATH: ./models
BATCH_SIZE: 10
SHAPE: 128
N_SAMPLES: 5000 
PLOT_INDEXES: [5, 10, 15, 20, 50, 30, 16, 17, 18, 19, 22, 23, 24]
SAVE_DIR: report/unets

PLOT_SCALE_FACTOR: 2
SAVE_PREDS: False